version: '3.8'
services:
  db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_booking
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-backend
    env_file:
      - .env
    ports:
      - "9001:9001"
    depends_on:
      - db

volumes:
  postgres_data: